### ISSUE TITLE
Hi! There I have a question. 

### ISSUE THREAD

**Issue by meezin** [MoMannn/delta_migration_script#1]
I was trying to use your delta_migration_Script but i don't know how to use it. 
What is connect.php file ? could you give me a hand for me a little bit?

1. I have a live site, a staging site(M v.1.9) and a dev site for M2. 
2. A live site in on A server 
    A staging site, which is clone site for live site and dev site is on B server. 
3. I can't find the way to migrate live site to dev site directly because they are on different DNS server. 
    I should clone all of database to staging site and run migration tool, anyway.
5. I already ran data mode from staging site to dev site.
6. I restored database to staging site from live site newly to run delta mode for dev site.
7. I tried delta mode migration. However i faced the same issue on post where https://github.com/magento/data-migration-tool/issues/316 is
8. I will run your script under `public_html` which i wrote as 

- $conm1 = mysqli_connect("localhost","dev_m2"," ","dev_m2");
- $conm2 = mysqli_connect("localhost","staging","","staging");

++ I have a question here : I'm a quite newbie to run script file. 
 1. Where do i put this file? under usr/bin?
 2.  What is the connect.php?

I will wait for your reply.

mary.kim@kbethos.com

**Comment by MoMannn** [comment]
This is what connect.php includes:

```
function conm1()
{
ob_start();

$host = "host";
$upImeBaza = "username";
$gesloBaza = "password";
$imeBaze = "databaseName";

$conn = mysqli_connect($host, $upImeBaza, $gesloBaza, $imeBaze);
mysqli_set_charset($conn, 'utf8');
ob_end_flush();
return $conn;
}

function conm2()
{
ob_start();

$host = "host";
$upImeBaza = "username";
$gesloBaza = "password";
$imeBaze = "databaseName";

$conn = mysqli_connect($host, $upImeBaza, $gesloBaza, $imeBaze);
mysqli_set_charset($conn, 'utf8');
ob_end_flush();
return $conn;
}
```

You can put the script anywhere on the server you just need to make sure it can connect to both databases.

I would advice you to connect directly M1 database and migrate via default migration tool since that makes things much simpler.
