### ISSUE TITLE
Huge DB

### ISSUE THREAD

**Issue by daweedco** [MoMannn/delta_migration_script#3]
Hello , nice of you to make your script available,

when i have a really big table (the delta must be 300k rows) , it's just disconnecting with error from ssh saying broken pipe

Can you please help me ?

**Comment by MoMannn** [comment]
I would suggest adding limits so it processes less rows at a time and running the script a few time for 50k rows at a time or something like this. The script is not really optimised.

**Comment by daweedco** [comment]
in which query would you suggest adding the limit ?
Thanks

**Comment by MoMannn** [comment]
Sorry I haven't really looked at the script in 3 years so I am not really sure. From what I remember the script goes first to check which ids are to be ignored and based on that transfers data so It could be a problem optimising for a larger db.
